// test/tutorworkspace/QandAList/QandAListPage_style.js

export const qandaListPageStyles = {
    container: {
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        p: 0,
    },
    topHeader: {
        bgcolor: 'primary.main',
        height: '100px',
        borderTopLeftRadius: '16px',
        borderTopRightRadius: '16px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'flex-start',
        color: 'white',
        p: 3,
        mt: -4,
        ml: -4,
        mr: -4,
        width: 'calc(100% + 64px)',
    },
    headerTitle: {
        color: 'white',
        fontWeight: 600,
        fontSize: '1.75rem',
    },
    contentArea: {
        bgcolor: '#EFF8FF',
        borderBottomLeftRadius: '16px',
        borderBottomRightRadius: '16px',
        p: 4,
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        gap: 3,
        overflowY: 'auto',
    },
    controlSection: {
        display: 'flex',
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    uploadButton: {
        bgcolor: 'primary.main',
        color: 'white',
        fontWeight: 600,
        px: 3,
        py: 1.5,
        borderRadius: '25px',
        fontSize: '1rem',
        textTransform: 'none',
        '&:hover': {
            bgcolor: 'primary.dark',
        },
    },
    qaList: {
        bgcolor: 'white',
        borderRadius: '12px',
        border: '1px solid #E2E8F0',
        overflow: 'hidden',
        flex: 1,
    },
    qaItem: {
        display: 'flex',
        alignItems: 'center',
        px: 3,
        py: 2,
    },
    fileIcon: {
        mr: 2,
        display: 'flex',
        alignItems: 'center',
    },
    qaInfo: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        gap: 0.5,
    },
    fileName: {
        color: 'text.primary',
        fontSize: '1rem',
        fontWeight: 500,
    },
    fileDetails: {
        color: 'text.secondary',
        fontSize: '0.875rem',
    },
    emptyState: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        color: 'text.secondary',
    },
    emptyIcon: {
        fontSize: '64px',
        mb: 2,
        color: 'text.disabled',
    },
};