version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0827
      POSTGRES_DB: unitask
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "6543:5432"

  backend:
    build: .
    ports:
      - "8008:8008"
    depends_on:
      - db
    env_file:
      - .env
volumes:
  pgdata: